# Handle git submodules yourself
git:
    submodules: false
sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.cache/packpack
language: C

env:
    matrix:
      - OS=centos DIST=6
      - OS=centos DIST=7
      - OS=fedora DIST=23
      - OS=fedora DIST=24
      - OS=ubuntu DIST=trusty
      - OS=ubuntu DIST=precise
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=yakkety
      - OS=debian DIST=jessie
      - OS=debian DIST=wheezy
      - OS=debian DIST=stretch

script:
 - git submodule update --init --recursive || true
  # Build packages using PackPack
 - git clone --depth 1 https://github.com/benoit-pierre/packpack.git packpack
 - packpack/packpack

deploy:
  # Deploy packages to PackageCloud
  provider: packagecloud
  username: ${PACKAGECLOUD_USER}
  repository: ${PACKAGECLOUD_REPO}
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: build/*.{deb,rpm}
  skip_cleanup: true
  on:
    branch: auto-build
    condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
